<script lang="ts">
  import { page } from '$app/stores';
  import { onMount } from 'svelte';
  import { money, fmtSigned } from '$lib/utils/money';
  import { prettyDate, buildStatementCSV, downloadText, statementFilename } from '$lib/utils/statement';

  let user = $derived($page.data?.user ?? null);
  let stats = $state<any>(null);
  let loading = $state(true);

  const generated = prettyDate(new Date().toISOString());

  async function load() {
    if (!user) { loading = false; return; }
    try {
      const res = await fetch(`/api/users/${encodeURIComponent(user.handle)}/stats`);
      const data = await res.json();
      stats = data.stats;
    } catch {}
    finally { loading = false; }
  }
  onMount(load);

  function csv() {
    if (stats) downloadText(statementFilename(user.handle, 'csv'), buildStatementCSV(user, stats));
  }

  // A run only counts as a "streak" at 3+ (matches the profile + game-share tag) —
  // losing one night isn't a cold streak.
  const streakLabel = (s: any) => (!s || (s.current ?? 0) < 3 || s.kind === 'none' ? '—' : `${s.current}${s.kind === 'win' ? 'W' : 'L'}`);
</script>

<svelte:head><title>potcount — statement</title></svelte:head>

<div class="wrap py-6">
  <div class="no-print flex items-center justify-between gap-3 mb-4">
    <a href="/account" class="text-sm text-muted hover:text-text">← Account</a>
    {#if stats}
      <div class="flex gap-2">
        <button class="btn-small btn-secondary" onclick={csv}>Export CSV</button>
        <button class="btn-small btn" onclick={() => window.print()}>Save as PDF</button>
      </div>
    {/if}
  </div>

  {#if loading}
    <div class="text-muted text-sm">Loading your statement…</div>
  {:else if !user}
    <div class="card">Please <a href="/account">sign in</a> to view your statement.</div>
  {:else if !stats || !stats.ledger?.length}
    <div class="card text-muted text-sm">No settled games yet — play a night and your statement will appear here.</div>
  {:else}
    <!-- The printable sheet: a light "paper" document that reads well on screen
         and prints cleanly (see @media print). -->
    <div class="sheet">
      <header class="sheet-head">
        <div class="brand">
          <img src="/favicon.svg" alt="" width="40" height="40" />
          <span>potcount</span>
        </div>
        <div class="sheet-meta">
          <div class="stmt-title">Player statement</div>
          <div>@{user.handle} · generated {generated}</div>
          <div>Amounts in {stats.unit}{stats.otherGames ? ' (other-unit games shown in their own unit)' : ''}</div>
        </div>
      </header>

      <section class="summary">
        <div class="s-cell"><span class="s-val" class:pos={stats.totalProfit >= 0} class:neg={stats.totalProfit < 0}>{fmtSigned(stats.totalProfit, stats.unit)}</span><span class="s-lbl">Total profit</span></div>
        <div class="s-cell"><span class="s-val">{stats.gamesPlayed}</span><span class="s-lbl">Games played</span></div>
        <div class="s-cell"><span class="s-val" class:pos={stats.avgProfit >= 0} class:neg={stats.avgProfit < 0}>{stats.gamesPlayed ? fmtSigned(stats.avgProfit, stats.unit) : '—'}</span><span class="s-lbl">Avg / game</span></div>
        <div class="s-cell"><span class="s-val">{stats.gamesPlayed ? stats.profitablePct + '%' : '—'}</span><span class="s-lbl">Win rate</span></div>
        <div class="s-cell"><span class="s-val pos">{stats.best ? fmtSigned(stats.best.net, stats.unit) : '—'}</span><span class="s-lbl">Best night</span></div>
        <div class="s-cell"><span class="s-val neg">{stats.worst ? fmtSigned(stats.worst.net, stats.unit) : '—'}</span><span class="s-lbl">Worst night</span></div>
        <div class="s-cell"><span class="s-val">{stats.gamesPlayed ? money(stats.avgBuyIn, stats.unit) : '—'}</span><span class="s-lbl">Avg buy-in</span></div>
        <div class="s-cell"><span class="s-val">{streakLabel(stats.streak)}</span><span class="s-lbl">Current streak</span></div>
      </section>

      <table class="ledger">
        <thead>
          <tr><th>Date</th><th>Game</th><th class="num">Buy-in</th><th class="num">Net</th></tr>
        </thead>
        <tbody>
          {#each stats.ledger as r (r.id)}
            <tr>
              <td class="date">{prettyDate(r.at)}</td>
              <td class="game">{r.name} <span class="gid">#{r.id}</span></td>
              <td class="num">{money(r.invested, r.unit)}</td>
              <td class="num" class:pos={r.net >= 0} class:neg={r.net < 0}>{fmtSigned(r.net, r.unit)}</td>
            </tr>
          {/each}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="3" class="tot-lbl">Total ({stats.gamesPlayed} counted game{stats.gamesPlayed === 1 ? '' : 's'})</td>
            <td class="num tot-val" class:pos={stats.totalProfit >= 0} class:neg={stats.totalProfit < 0}>{fmtSigned(stats.totalProfit, stats.unit)}</td>
          </tr>
        </tfoot>
      </table>

      <footer class="sheet-foot">
        Generated by potcount · potcount.app · This is a personal record of home-game results, not a financial or tax document.
      </footer>
    </div>
  {/if}
</div>

<style>
  /* Light "paper" sheet — reads as a document on the dark app and prints clean. */
  .sheet {
    background: #ffffff;
    color: #1a1c1e;
    border-radius: 16px;
    padding: 34px 34px 26px;
    box-shadow: 0 12px 40px -18px rgba(0, 0, 0, 0.6);
    font-size: 14px;
  }
  .sheet-head {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 16px;
    border-bottom: 2px solid #ecebe7;
    padding-bottom: 18px;
  }
  .brand { display: flex; align-items: center; gap: 10px; font-family: var(--font-display); font-weight: 700; font-size: 22px; color: #111; }
  .sheet-meta { text-align: right; color: #6b7075; font-size: 12px; line-height: 1.5; }
  .stmt-title { font-weight: 700; color: #1a1c1e; font-size: 15px; }

  .summary {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 10px;
    margin: 22px 0;
  }
  .s-cell {
    display: flex;
    flex-direction: column;
    gap: 3px;
    padding: 12px 12px;
    border: 1px solid #ecebe7;
    border-radius: 10px;
    background: #faf9f7;
  }
  .s-val { font-family: var(--font-display); font-weight: 700; font-size: 19px; font-variant-numeric: tabular-nums; }
  .s-lbl { font-size: 11px; color: #6b7075; text-transform: uppercase; letter-spacing: 0.05em; }

  .ledger { width: 100%; border-collapse: collapse; margin-top: 8px; }
  .ledger th, .ledger td { padding: 9px 8px; text-align: left; }
  .ledger thead th {
    font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em;
    color: #6b7075; border-bottom: 1.5px solid #e2e0db;
  }
  .ledger tbody tr { border-bottom: 1px solid #f0efec; }
  .ledger .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
  .ledger .date { white-space: nowrap; color: #4a4e52; }
  .ledger .game { font-weight: 600; }
  .gid { color: #a7abae; font-weight: 400; font-size: 12px; }
  .ledger tfoot td { padding-top: 12px; border-top: 2px solid #e2e0db; font-weight: 700; }
  .tot-lbl { text-align: right; color: #4a4e52; }
  .tot-val { font-family: var(--font-display); }

  .pos { color: #0f8a54; }
  .neg { color: #d23b46; }
  .sheet-foot { margin-top: 20px; padding-top: 14px; border-top: 1px solid #ecebe7; color: #8b8f93; font-size: 11px; text-align: center; }

  @media (max-width: 520px) {
    .summary { grid-template-columns: repeat(2, 1fr); }
    .gid { display: none; }
  }

  /* Print: isolate the sheet, drop the app chrome and shadow. */
  @media print {
    :global(body) { background: #fff; }
    :global(body *) { visibility: hidden; }
    .sheet, .sheet * { visibility: visible; }
    .sheet { position: absolute; inset: 0; margin: 0; box-shadow: none; border-radius: 0; }
    .no-print { display: none; }
  }
</style>
